/**
 * Artist Data Service
 * 
 * Fetches artist data from the static JSON file generated by GitHub Actions
 */

/**
 * Fetch artists data from the static JSON file
 * @returns {Promise<Object>} Artists data with metadata
 */
export async function fetchArtistsData() {
  try {
    console.log('📡 Fetching artists data from static JSON...');

    // Fetch from the public directory (same domain as the app)
    // Add cache-busting to ensure fresh data
    const response = await fetch('/artists.json', { cache: 'no-cache' });

    if (!response.ok) {
      throw new Error(`Failed to fetch artists data: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();

    console.log(`✅ Loaded ${data.totalArtists} artists from static data`);
    console.log(`🕒 Data last updated: ${data.lastUpdated}`);

    return data;

  } catch (error) {
    console.error('❌ Error fetching artists data:', error);

    // Return fallback data if fetch fails
    return {
      artists: [],
      lastUpdated: new Date().toISOString(),
      totalArtists: 0,
      source: "Fallback",
      error: error.message
    };
  }
}

/**
 * Get formatted last updated time
 * @param {string} isoString - ISO date string
 * @returns {string} Formatted date string
 */
export function formatLastUpdated(isoString) {
  try {
    const date = new Date(isoString);

    // Check for invalid date
    if (isNaN(date.getTime())) {
      console.error('Invalid date string provided:', isoString);
      return 'Unknown';
    }

    const now = new Date();
    const diffMs = now - date;
    const diffMinutes = Math.floor(diffMs / (1000 * 60));
    const diffHours = Math.floor(diffMinutes / 60);
    const diffDays = Math.floor(diffHours / 24);

    if (diffMinutes < 1) {
      return 'Just now';
    } else if (diffHours < 1) {
      return `${diffMinutes} minute${diffMinutes === 1 ? '' : 's'} ago`;
    } else if (diffHours < 24) {
      return `${diffHours} hour${diffHours === 1 ? '' : 's'} ago`;
    } else if (diffDays < 7) {
      return `${diffDays} day${diffDays === 1 ? '' : 's'} ago`;
    } else {
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
    }
  } catch (error) {
    console.error('Error formatting date:', error);
    return 'Unknown';
  }
}

/**
 * Sort artists by play count (descending)
 * @param {Array} artists - Array of artist objects
 * @returns {Array} Sorted artists array
 */
export function sortArtistsByPlayCount(artists) {
  return [ ...artists ].sort((a, b) => (b.playCount || 0) - (a.playCount || 0));
}

/**
 * Filter artists by name (case-insensitive)
 * @param {Array} artists - Array of artist objects
 * @param {string} searchTerm - Search term
 * @returns {Array} Filtered artists array
 */
export function filterArtistsByName(artists, searchTerm) {
  if (!searchTerm.trim()) {
    return artists;
  }

  const term = searchTerm.toLowerCase();
  return artists.filter(artist =>
    artist.name.toLowerCase().includes(term)
  );
}

/**
 * Get artist statistics
 * @param {Array} artists - Array of artist objects
 * @returns {Object} Statistics object
 */
export function getArtistsStats(artists) {
  const totalPlayCount = artists.reduce((sum, artist) => sum + (artist.playCount || 0), 0);
  const avgPlayCount = artists.length > 0 ? Math.round(totalPlayCount / artists.length) : 0;

  return {
    totalArtists: artists.length,
    totalPlayCount,
    avgPlayCount,
    mostPlayed: artists.length > 0 ? Math.max(...artists.map(a => a.playCount || 0)) : 0
  };
}

export default {
  fetchArtistsData,
  formatLastUpdated,
  sortArtistsByPlayCount,
  filterArtistsByName,
  getArtistsStats
};
